chicago_crimes/chicago_crimes/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = [
               url(r'^viewer/', include('viewer.urls')),
               url(r'^admin/', include(admin.site.urls)),

               ]

chicago_crimes/viewer/urls.py
from django.conf.urls import url

from . import views


app_name = 'viewer'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<year>[0-9]+)/$', views.by_year, name='by_year'),
]

chicago_crimes/viewer/models.py
# python general imports
import os

# geodjango specific imports

from django.contrib.gis.db import models
from django.contrib.gis import forms

from django.contrib.gis.utils import LayerMapping



class Ward(models.Model):
    ward = models.CharField(max_length=4, primary_key=True)
    shape_leng = models.FloatField(null=True)
    shape_area = models.FloatField(null=True)
    geom = models.MultiPolygonField(srid=4269, null=True)
    objects = models.GeoManager()

    # Returns the string representation of the model.
    # Return string representation of Ward

    def __unicode__(self):
        return u'Ward ID is: %s' % (self.ward)

class Crime(models.Model):
    original_id = models.CharField(max_length=200)
    arrest = models.BooleanField(default=False)
    date = models.DateTimeField(db_index=True)
    domestic = models.BooleanField(default=False)
    latitude = models.DecimalField(max_digits=14, decimal_places=12)
    longitude = models.DecimalField(max_digits=14, decimal_places=12)
    primary_type = models.CharField(max_length=500)
    ward = models.ForeignKey(
            Ward,
            blank = True,
            null = True
    )

    # GeoDjango specific model attributes

    point = models.PointField(srid=4326, null=True, blank=True)
    objects = models.GeoManager()

    # Return string representation of Crime

    # def __unicode__(self):
    #     return '%s' % (self)

# Auto-generated `LayerMapping` dictionary for Ward model

ward_mapping = {
    'ward': 'WARD',
    'shape_leng': 'SHAPE_Leng',
    'shape_area': 'SHAPE_Area',
    'geom': 'MULTIPOLYGON',
}

chicago_crimes/viewer/views.py
# Django Views imports

from django.shortcuts import render, get_list_or_404
from django.http import JsonResponse

# Django Models imports

from django.db.models import Count

# App Models imports

from .models import Crime


def index(request):
    years_for_data = [a.year for a in set(Crime.objects.datetimes('date', 'year', order='DESC'))]
    context = {
        'years_for_data': years_for_data
    }
    return render(
        request,
        'viewer/index.html',
        context
    )


def by_year(request, year):
    """
    The intended result here is to have aggregate data for wards for the year given.
    Example: in 2002, ward 17 had this many crimes, this many arrests, this many types of crimes, this many crimes/type

    This is to be JSON for JavaScript.

    Right now though this is the closest I can get:
    q=Crime.objects.values('ward').annotate(cc=Count('pk')).values('ward', 'cc').order_by('ward')

    What I would like to see added to this is a count by primary_type by ward, so, after we get the total_count_by ward, another level down
    would be ptypeA: 1, ptypeB:1, etc.
    """

    # crimes = Crime.objects.values().filter(date__year=year)

    crimes = Crime.objects.values('ward') \
        .annotate(total_crime_count=Count('pk')) \
        .values('ward', 'total_crime_count') \
        .order_by('ward') \
        .filter(date__year=year)


    return JsonResponse(list(crimes), safe=False)

chicago_crimes/viewer/templates/viewer/byYear.html
{{ crimes }}

chicago_crimes/viewer/templates/viewer/index.html
<!DOCTYPE html>
{% load staticfiles %}


<html>
<head>
    <title> Crimes in Chicago </title>
    <link rel="stylesheet" type="text/css" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.css' %}">
    <script type="text/javascript" href="{% static 'node_modules/d3/d3.js' %}"></script>
    <style type="text/css">

        body {
            font: 12px sans-serif;
        }

        .axis path,
        .axis line {
            fill: none;
            stroke: #000;
            shape-rendering: crispEdges;
        }

        .x.axis path {
            fill: none;
            stroke: #000;
            shape-rendering: crispEdges;
        }

        .line {
            fill: none;
            stroke-width: 7px;
        }

        .country {
            opacity: 0.3;
        }

        .country:hover {
            opacity: 1;
        }

    </style>
</head>
<body>
<div>
    <input type="checkbox" id="domestic" onclick="domesticLight()">Domestic Violence Incidents</input>
    <input type="checkbox" id="nondomestic" onclick="nondomesticLight()">Non-DV Incidents</input>
</div>
<script>
    var margin = {top: 30, right: 20, bottom: 30, left: 50},
            width = 600 - margin.left - margin.right,
            height = 270 -margin.top - margin.right;

</script>

{% if years_for_data %}
    <b>Years Reported</b>
    <ul>
        {% for year in years_for_data %}
            <li><a href="{% url 'viewer:by_year' year %}">{{ year }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>There are no years of data available</p>
{% endif %}
</body>

</html>